### ISSUE TITLE
Mismatch between OTG and centerline site names

### ISSUE THREAD

**Issue by KevinSee** [mackerman44/DASH#30]
Some of the site_names in the OTG survey data don't match with the centerline Site_ID. Things like LowerLemhi3_2019 vs. Lowerlemhi3_2019, or Lower Lemhi_2, or even "Lemhi River". We can fix this by hand when matching the two datasets up, but it would be good to establish a better process, maybe pre-loading site names into Survey123 or something?

**Comment by mackerman44** [comment]
I believe I've resolved this.
