### ISSUE TITLE
Resolve Station Widths

### ISSUE THREAD

**Issue by mackerman44** [mackerman44/DASH#33]
According to @rcarmichael3 Ricardo, *"station width refers to the distance **between** each depth and velocity measurement, so they should be the same across each measurement. So if all of them are 0.25 or 0.64 that would make sense to me. At least that is how it is supposed to be recorded."*

This was in response to @KevinSee's earlier remarks to me *"I also noticed that a number of the discharge metrics for 2020 are 0, which seems odd. Looking at the discharge measurements, it looks like maybe the station widths weren’t captured correctly? For example, in the Grouse Discharge_Measurements_6.csv file, all the station widths are either 0.25 or 0.64. Seems odd, no?"*

So it seems we need to review how measurements are collected and discharge is calculated. 1) It appears that station width's may have been collected incorrectly in 2018 & 2019, at least after first glance. However, 2) this doesn't necessarily explain Kevin's remark above where a number of the discharge metrics for 2020 are 0.

In any case, worth a review.

**Comment by KevinSee** [comment]
In 2019, the station widths were all measured as the distance from one bank, so they increased steadily across one transect. In 2020, the station widths were nearly all measured as the distance between stations, so they're all nearly identical for each transect. Clearly we need to settle on one method or the other, and transform one year's worth of data to match the other, so our calc_discharge function can work correctly. @rcarmichael3 or @mackerman44, which is easier to measure in the field?

I know that calculating discharge involves knowing the distance between stations, so currently the function uses the difference in station widths to calculate that (since the 2019 widths are from a single point on the bank).

**Comment by KevinSee** [comment]
So I'm trying to resolve the `calc_discharge()` function to work with station widths that represent the distance from the previous station to the current one (at least that's how I'm interpreting the 2020 data). However, some (but not all) of the discharge measurements in 2020 show increasing station depths up to a max, and then it stops. I was expecting the depths to decrease back to 0 or close to it. They appear like someone only took discharge measurements out to the middle of the stream. Or they flipped over to a new parent global ID halfway through the stream. For example, the Lake Creek survey, the first 2 parent global IDs look like maybe they should have been the same? The depths increase during the first, then start high for the 2nd and decrease. 

2nd question: the last discharge measurement station is never at a depth of 0. I'm assuming the first measurement shows the width from the bank to the first station (and the second width is the distance between the first and second station, etc.). That means the last station width is the distance between the second-to-last station, and the last station, but we don't know the distance from the last station to the second bank. I think we need that measurement to calculate discharge correctly, based on the CHaMP description here: (https://www.monitoringresources.org/Document/Method/Details/853)

**Comment by KevinSee** [comment]
The current protocol does not explicitly say how to record station widths. It should be updated so everything is consistent.

**Comment by mackerman44** [comment]
I've updated the **Discharge Measurements** section in the DASH protocol. Step 3 now reads as follows:

**Measure width, depth, and velocity for each station.**
a.	Stand downstream of the velocity meter when taking measurements. 
b.	If the depth is 0, which it likely should be at both the left and right banks, record the velocity as 0.
c.	If the velocity is negative (-), record the measured velocity.
d.	At each station, record the station width as the distance from the previous station to the current one, starting with the left bank.
    i.	For the first, left bank, the station width should be zero, as should likely be the depth and velocity.
    ii.	For the last, right bank, the station width may be different and will be the distance from the last wetted station to the edge of the wetted width. In this case, the depth and velocity should also likely be zero. If the distance from the previous wetted station to the edge of the wetted width is less than 0, simply move the last station to the edge of the wetted width and update the station width to reflect that.
    iii.	The sum of the station widths should be equal to the total wetted width.
e.	Place the topset rod in the stream at the interval point and record the water depth. Set the topset rod to the correct height. This will raise or lower the velocity probe to 60% of the water depth at that interval. Position the velocity probe directly perpendicular to the stream channel and hold the topset rod vertically level. Wait for the progress on the velocity meter to go through a full 10 second cycle (i.e., fully through 0% to 100%). Record the velocity. Move to the next interval point and repeat the same procedure until depth and velocity measurements have been recorded for all intervals. 

How does that look?

**Comment by mackerman44** [comment]
I believe this is all resolved.
