### ISSUE TITLE
Acceptable Undercut Location

### ISSUE THREAD

**Issue by KevinSee** [mackerman44/DASH#8]
What are the acceptable values for Location in the Undercut csv? In the 2019 data, almost all of them are either "Right_Bank" or "Left_Bank", which make sense. However, there are a few weird ones, such as:

- "Island": 2 

- "Island,Right_Bank": 1

- "Right_Bank,Left_Bank": 3

Realizing that if a surveyor finds an undercut on an island, there should be some way to identify where it is. But then I think it should either just be "Island" for somewhere on an island, or "Island,Left_Bank" / "Island,Right_Bank".

Currently, the QA/QC function flags anything other than "Right_Bank" and "Left_Bank"

**Comment by mackerman44** [comment]
Boom, resolved
